name: C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vcpkg_bootstrap:
    runs-on: ubuntu-latest
    container: 
      image: debian:stable-slim

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential cmake git curl zip unzip

    - name: Bootstrap vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git ./_vcpkg_
        cd _vcpkg_
        git checkout -b specific 3508985146f1b1d248c67ead13f8f54be5b4f5da
        ./bootstrap-vcpkg.sh -disableMetrics
        
    - name: Upload vcpkg artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vcpkg
        include-hidden-files: true # So that .vcpkg-root is included
        path: ./_vcpkg_

  build:
    runs-on: ubuntu-latest
    container: 
      image: debian:stable-slim
    needs: vcpkg_bootstrap
    
    env:
      VCPKG_TARGET_TRIPLET: x64-linux  # Define the target triplet

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download vcpkg artifacts
      uses: actions/download-artifact@v4
      with:
        name: vcpkg
        path: ./_vcpkg_
        
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y build-essential cmake git curl zip unzip pkg-config autoconf automake autotools-dev
        
    - name: Create build directory
      run: mkdir _build_ && cd _build_

    - name: Build the project
      run: |
        chmod +x ./_vcpkg_/vcpkg
        cd _build_
        cmake -DCMAKE_BUILD_TYPE=Release ..
        cmake --build . -j 4
        
