name: C++ CI

on:
  push:
    branches:
      - main
      - new-ci-workflow-based-on-run-vcpkg
  pull_request:
    branches:
      - main

jobs:
  build_with_run_vcpkg:
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_TRIPLET: x64-linux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Get cmake
        uses: lukka/get-cmake@latest
      
      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        id: runvcpkg
        with:
          # This specifies the location of vcpkg, where it is going to be restored from cache, or create from scratch.
          vcpkgDirectory: '${{ github.workspace }}/_vcpkg_'

      - name: Run CMake with vcpkg.json manifest
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          configurePreset: vcpkg-cmake-build
          buildPreset: vcpkg-cmake-release
          
